### ISSUE TITLE
Create function in home.js for search functionality.

### ISSUE THREAD

**Issue by hetsonii** [Joyshah62/E-Library#4]
All the books in book.js (and fiction.js, thriller.js, novel.js, selfhelp.js) have the following js logic for each book.

> (resultWords.some(word => "Book Name".toLowerCase().includes(word.toLowerCase())) &&
>                                 "Book Name".toLowerCase().includes(searchValue.toLowerCase())) && (

Provide a more efficient solution for searching functionality or create an easily modifiable function which replaces this logic.

**Comment by Joyshah62** [comment]
Hey, thanks for taking interest. You can work on the issue!

**Comment by ijklmopffs** [comment]
Hello, can we connect on telegram or discord?

**Comment by hetsonii** [comment]
Sure. Can you drop your id?

**Comment by ijklmopffs** [comment]
Sure, https://t.me/Jkmnopffs
