### ISSUE TITLE
Login Page Improvements

### ISSUE THREAD

**Issue by hetsonii** [Joyshah62/E-Library#6]
Show unmet password requirements when clicked 'Sign in' or 'Create New Account'. Currently it allows users to create new accounts without having met the password requirements. Regex improvement is allowed. Current regex for email and password check is - 

> (Email) pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" 
> (Password) pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,12}$"

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by Joyshah62** [comment]
hey @tarunsamanta2k20 , thanks for taking interest. You can work on this!

**Comment by hetsonii** [comment]
unassigning due to inactivity.

**Comment by hetsonii** [comment]
New login page UI has been implemented which does not have the given regex checks. 
Future development may consist of the password requirements.
