### ISSUE TITLE
Books genre Filter Enhancement

### ISSUE THREAD

**Issue by hetsonii** [Joyshah62/E-Library#7]
Create a solution to remove all the genres files (thriller.js, selfhelp.js, novel.js, fuction.js) and show only books in selected genre on the home page only. 
As a temporary solution, user is redirected to a different page when selected a specific genre.

**Comment by willdelorm** [comment]
Hey @hetsonii, I'd be happy to take a look at this. :)

**Comment by Joyshah62** [comment]
Hey @willdelorm, you can work on this!

**Comment by hetsonii** [comment]
I had opened #4  to resolve the same issue and @ijklmopffs is assigned to that issue.
Hey @ijklmopffs, if you haven't started to implement the function, can you please shift to implement this method that @willdelorm has mentioned in above comment?
sorry for the late response.

**Comment by ijklmopffs** [comment]
Alright, will get started on that

**Comment by hetsonii** [comment]
Hey @willdelorm! I've created books.db.js 
Can you help me with the original issue? Do open new issues for enhancement and feature suggestions :)

**Comment by hetsonii** [comment]
Issue was solved in [this](https://github.com/Joyshah62/E-Library/commit/c123421f16d01c835fa626d18e47e483c606777b) commit. 
Thanks everyone for inputs.
